version: '3.6'
services:
  nginx_connect:
    image: rtmtb/nginx_connect
    hostname:  nginx_connect
    ports:
      - "3128:3128" # Proxy port
    # entrypoint: "tail -f /dev/null" # use to keep the container open for debugging
    entrypoint: ./init_and_run.sh
    volumes:
    - nginx.conf:/etc/nginx/nginx.conf
